import localFont from "next/font/local";
import "./globals.css"; 
import { ThemeProvider } from "../../context/ThemeContext";
import { GlobalProvider } from "../../context/GlobalContext";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Home page",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider>
          <GlobalProvider>
          {children}
          </GlobalProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
